### ISSUE TITLE
magic?

### ISSUE THREAD

**Issue by zvezdochiot** [fridex/rscode-correction#4]
Maybe use `magic`? Sample: `RSECC74.` - `RSECC4096.`.

**Comment by zvezdochiot** [comment]
See https://github.com/zagalskij/HammingCode/pull/5

How is this better done in C++?

**Comment by fridex** [comment]
You can use `std::ostream::write` [1] to write the magic into the output stream and use `std::istream::read` to read the magic if required. Both methods can be used on a C-like string buffer with a fixed size, so standard C's `strncmp` [3] will work.

[1] http://www.cplusplus.com/reference/istream/istream/get/
[2] http://www.cplusplus.com/reference/ostream/ostream/write/
[3] http://www.cplusplus.com/reference/cstring/strncmp/

**Comment by zvezdochiot** [comment]
HELP WANTED.

To add `magic`, I applied a simple solution:
```cpp
    std::cout << "Size = " << data.size() << "\n" << std::endl;
#ifdef BMS1A
    char mc[4];
    file_out.write("RSECC", 5);
    sprintf(mc, "%d", blocksize);
    file_out.write(mc, 4);
#endif // BMS1A
    std::cout << "Size = " << data.size() << "\n" << std::endl;
```
Not works. This causes the data.size() to change from 18092 to 18340.
```sh
./rsenc LICENSE 1024
```
HELP WANTED.

**Comment by fridex** [comment]
> HELP WANTED.
> 
> To add `magic`, I applied a simple solution:
> 
> ```c++
>     std::cout << "Size = " << data.size() << "\n" << std::endl;
> #ifdef BMS1A
>     char mc[4];
>     file_out.write("RSECC", 5);
>     sprintf(mc, "%d", blocksize);
>     file_out.write(mc, 4);
> #endif // BMS1A
>     std::cout << "Size = " << data.size() << "\n" << std::endl;
> ```
> 
> Not works. This causes the data.size() to change from 18092 to 18340.
> 
> ```shell
> ./rsenc LICENSE 1024
> ```
> 
> HELP WANTED.

Can you open a PR with the modified code (even thought it does not work) so I see the whole context?

BTW note `sprtintf` is automatically appending null character into `mc`, so if the blocksize has 4 and more digits, your write to wrong memory.

**Comment by zvezdochiot** [comment]
@fridex say:
>BTW note sprtintf is automatically appending null character into mc, so if the blocksize has 4 and more digits, your write to wrong memory.

Best. Fixed.

**Comment by zvezdochiot** [comment]
PR https://github.com/fridex/rscode-correction/pull/5
